/* Copilot follows Pilot or Bridge. No receiver transport commands are accepted. */
(function(){'use strict';
const viewer=document.body.hasAttribute('data-copilot-viewer'),$=id=>document.getElementById(id),peers=new Map(),visuals=new Map();let session,events,latest,lastReceived=0,revision=0,signalQueue=Promise.resolve(),shareLink='',lastSend=0,renderKey='',connecting,relay=false,relayBusy=false,relayTimer,relayStamp=0;const relayKnown=new Map(),relaySent=new Map();
const en=()=>window.S2ALanguage?S2ALanguage.language==='en':latest?.language==='en',say=(fr,eng)=>en()?eng:fr;
function status(text){const el=$(viewer?'copilotConnection':'copilotShareStatus');if(el)el.textContent=text;}
function route(name){return new URL('./api/'+name,location.href).pathname;}
function endpoint(name){return route(name)+'?session='+session.id+'&key='+session.key+(session.peer?'&peer='+session.peer:'');}
async function request(url,data){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data||{})});if(!r.ok)throw Error(say('Partage indisponible ou expiré. Vérifiez la connexion et le service Copilot de cet hébergement.','Sharing unavailable or expired. Check the connection and this hosting’s Copilot service.'));return r.json();}
function relayUrl(action){return new URL('./copilot-api.php?action='+action,location.href).href;}
function acceptState(s){if(!validState(s))return;if(Array.isArray(s.visualIds)){for(const id of visuals.keys())if(!s.visualIds.includes(id)){visuals.delete(id);relayKnown.delete(id);renderKey='';}}latest=s;if(window.S2AStartup)S2AStartup.setLanguage(s.language);lastReceived=performance.now();status(say('Connecté · lecture seule','Connected · read only'));}
async function pollRelay(){
 if(!session||relayBusy)return;relayBusy=true;const current=session;
 try{const packet=await request(relayUrl('snapshot'),{session:current.id,key:current.key,known:Object.fromEntries(relayKnown)});if(current!==session)return;
  for(const v of packet.visuals||[])if(typeof v.id==='string'&&typeof v.src==='string'&&/^data:image\/jpeg;base64,/.test(v.src)&&v.src.length<50000){visuals.set(v.id,v.src);relayKnown.set(v.id,v.hash);renderKey='';}
  if(packet.updatedAt>relayStamp){relayStamp=packet.updatedAt;acceptState(packet.state);}
 }catch(e){report(e);}finally{relayBusy=false;}
}
function validCue(c){return c&&typeof c.id==='string'&&c.id.length<200&&Number.isInteger(c.number)&&c.number>0&&Number.isFinite(c.time)&&c.time>=0&&typeof c.title==='string'&&c.title.length<=300&&typeof c.description==='string'&&c.description.length<=4000;}
function validState(s){return s&&s.type==='state'&&s.version===1&&Number.isFinite(s.time)&&s.time>=0&&Number.isFinite(s.duration)&&s.duration>=0&&typeof s.playing==='boolean'&&typeof s.title==='string'&&s.title.length<=300&&Array.isArray(s.cues)&&s.cues.length<=1000&&s.cues.every(validCue)&&['fr','en'].includes(s.language);}
function signal(type,value,id){return request(endpoint('signal'),{type,value,peer:id});}
function makePeer(id){const old=peers.get(id);if(old)old.pc.close();const pc=new RTCPeerConnection({iceServers:[]}),p={pc,pending:[],sentVisuals:new Map()};peers.set(id,p);pc.onicecandidate=e=>{if(e.candidate&&peers.get(id)===p)signal('ice',e.candidate.toJSON(),id).catch(report);};function attach(channel){p.channel=channel;channel.onopen=()=>{if(!viewer)status(say('Copilot connecté · lecture seule','Copilot connected · read only'));};if(viewer)channel.onmessage=e=>{if(typeof e.data!=='string'||e.data.length>64000)return;try{const s=JSON.parse(e.data);if(s.type==='visual'&&typeof s.id==='string'&&typeof s.src==='string'&&/^data:image\/jpeg;base64,/.test(s.src)&&s.src.length<50000){visuals.set(s.id,s.src);renderKey='';return;}acceptState(s);}catch(ignore){}};}
if(viewer)pc.ondatachannel=e=>attach(e.channel);else attach(pc.createDataChannel('s2a-show',{ordered:true}));return p;}
async function receive(m){if(m.type==='join'&&!viewer){const p=makePeer(m.peer);await p.pc.setLocalDescription(await p.pc.createOffer());await signal('offer',p.pc.localDescription.toJSON(),m.peer);return;}const id=viewer?'host':m.peer;let p=peers.get(id);if(m.type==='offer'&&viewer){p=makePeer(id);await p.pc.setRemoteDescription(m.value);await p.pc.setLocalDescription(await p.pc.createAnswer());await signal('answer',p.pc.localDescription.toJSON());}else if(m.type==='answer'&&!viewer&&p)await p.pc.setRemoteDescription(m.value);else if(m.type==='ice'&&p){if(p.pc.remoteDescription)await p.pc.addIceCandidate(m.value);else p.pending.push(m.value);}if(p&&p.pc.remoteDescription)while(p.pending.length)await p.pc.addIceCandidate(p.pending.shift());}
function stream(){events=new EventSource(endpoint('events'));events.onmessage=e=>{signalQueue=signalQueue.then(()=>receive(JSON.parse(e.data))).catch(report);};events.onerror=()=>{if(viewer&&!latest)status(say('Connexion en attente…','Waiting for connection…'));};}
function report(e){status(e.message||say('Connexion interrompue','Connection interrupted'));}
function stop(){clearInterval(relayTimer);relaySent.clear();if(session&&!viewer)request(relay?relayUrl('revoke'):endpoint('revoke'),relay?{session:session.id,key:session.key}:undefined).catch(()=>{});if(events)events.close();events=null;for(const p of peers.values())p.pc.close();peers.clear();session=null;shareLink='';if(!viewer){$('copilotShareLink').value='';$('copilotQr').replaceChildren();}status(say('Partage arrêté','Sharing stopped'));}
async function startHost(){if(session)return shareLink;if(connecting)return connecting;connecting=(async()=>{
 let s;
 const local=['localhost','127.0.0.1','[::1]'].includes(location.hostname);
 if(local&&!new URLSearchParams(location.search).has('copilotRelay')){s=await request(route('sessions'));relay=false;}
 else{
  try{s=await request(relayUrl('create'));if(s.transport!=='relay')throw Error();relay=true;}
  catch(e){throw Error(say('Le relais web Copilot est indisponible. Installez les fichiers de cette version, dont copilot-api.php, sur un hébergement PHP 8 en HTTPS.','The Copilot web relay is unavailable. Install this version’s files, including copilot-api.php, on PHP 8 HTTPS hosting.'));}
 }
 if(!relay&&!window.RTCPeerConnection)throw Error(say('Copilot nécessite un navigateur récent.','Copilot requires a recent browser.'));
 session={id:s.id,key:s.hostKey};const u=new URL('./copilot.html',location.href);const demo=new URLSearchParams(location.search).get('demo');if(demo)u.searchParams.set('demo',demo);u.searchParams.set('lang',en()?'en':'fr');u.hash='session='+s.id+'&key='+s.viewKey+(relay?'&transport=relay':'');shareLink=u.href;if(!relay)stream();return shareLink;
})();try{return await connecting;}finally{connecting=null;}}

const thumbs=new Map();function thumbnail(v){let cached=thumbs.get(v.id);if(cached?.source===v.src)return;cached={source:v.src,data:null};thumbs.set(v.id,cached);const img=new Image();img.onload=()=>{try{const c=document.createElement('canvas');c.width=320;c.height=180;const x=c.getContext('2d');x.fillStyle='#080a0d';x.fillRect(0,0,320,180);const scale=Math.min(320/img.width,180/img.height);x.drawImage(img,(320-img.width*scale)/2,(180-img.height*scale)/2,img.width*scale,img.height*scale);cached.data=c.toDataURL('image/jpeg',.55);if(cached.data.length>49000)cached.data=c.toDataURL('image/jpeg',.25);}catch(ignore){}};img.src=v.src;}
function publish(){if(!session||viewer||!window.S2ACopilotState)return;const source=S2ACopilotState();if(!source)return;const {visuals:images=[],...value}=source;const s={...value,type:'state',version:1,revision:++revision,visualIds:images.map(v=>v.id)};if(!validState(s))return;const text=JSON.stringify(s);if(text.length>64000){status(say('Conduite trop volumineuse pour le partage.','Show too large to share.'));return;}if(!relay)images.forEach(thumbnail);
if(relay){if(relayBusy||performance.now()-relayStamp<500)return;relayStamp=performance.now();relayBusy=true;const current=session;
 const active=s.cues.reduce((a,c,i)=>c.time<=s.time+.0001?i:a,-1),visibleIds=s.cues.slice(Math.max(0,active),Math.max(0,active)+5).map(c=>c.id),visibleImages=images.filter(v=>visibleIds.includes(v.id));visibleImages.forEach(thumbnail);for(const id of thumbs.keys())if(!visibleIds.includes(id))thumbs.delete(id);const updated=visibleImages.filter(v=>thumbs.get(v.id)?.data&&relaySent.get(v.id)!==v.src),packets=updated.map(v=>({id:v.id,src:thumbs.get(v.id).data}));
 request(relayUrl('publish'),{session:current.id,key:current.key,state:s,visibleIds,visuals:packets}).then(()=>{if(current!==session)return;for(const v of updated)relaySent.set(v.id,v.src);for(const id of relaySent.keys())if(!visibleIds.includes(id))relaySent.delete(id);}).catch(report).finally(()=>{relayBusy=false;});return;
}for(const p of peers.values()){if(p.channel?.readyState!=='open'||p.channel.bufferedAmount>128000)continue;p.channel.send(text);for(const v of images){const thumb=thumbs.get(v.id);if(thumb?.data&&p.sentVisuals.get(v.id)!==thumb.source){p.channel.send(JSON.stringify({type:'visual',id:v.id,src:thumb.data}));p.sentVisuals.set(v.id,thumb.source);}}}}
function fmt(t){return String(Math.floor(t/60)).padStart(2,'0')+':'+String(Math.floor(t%60)).padStart(2,'0');}
function element(tag,cls,value){const e=document.createElement(tag);e.className=cls;e.textContent=value||'';return e;}
function render(){if(!latest)return;const age=(performance.now()-lastReceived)/1000,stale=age>2,t=Math.min(latest.duration,latest.time+(latest.playing&&!stale?age:0));const index=latest.cues.reduce((a,c,i)=>c.time<=t+.0001?i:a,-1),active=latest.cues[index],next=latest.cues[index+1],remaining=next?Math.max(0,next.time-t):null,urgent=!stale&&remaining!==null&&remaining<=10;document.body.classList.toggle('nextCueUrgent',urgent);$('copilotConnection').classList.toggle('stale',stale);if(stale)status(say('Connexion interrompue · informations figées','Connection interrupted · information frozen'));document.documentElement.lang=latest.language;$('transportShowTitle').textContent=latest.title;$('showCuePosition').textContent='CUE '+(active?.number||0)+'/'+latest.cues.length;$('clock').textContent=fmt(t);$('duration').textContent='/ '+fmt(latest.duration);$('progress').style.width=(latest.duration?t/latest.duration*100:0)+'%';$('copilotCountdown').textContent=stale||remaining===null?'--:--':fmt(Math.ceil(remaining));document.querySelector('.showCountdownLabel').textContent=say('Décompte','Countdown');$('showNextCountdown').classList.toggle('isUrgent',urgent);const phase=remaining===null?0:remaining%1,beat=urgent?.25+.75*Math.pow(Math.cos(Math.PI*phase),8):0;$('showCountdownBeat').style.opacity=String(beat);
const shown=latest.cues.slice(Math.max(0,index),Math.max(0,index)+5),key=JSON.stringify([latest.language,shown,Array.from(visuals.keys()),index]);if(key!==renderKey){renderKey=key;$('showCueOverviewRows').replaceChildren();for(const c of shown){const row=element('div','showOverviewRow'+(c===active?' isActive':'')+(c===next?' isNext':'')),v=element('div','overviewVisual showOverviewPlaceholder');if(visuals.has(c.id)){const img=new Image();img.src=visuals.get(c.id);img.alt='';v.append(img);}else v.textContent=say('Pas de visuel','No visual');const content=element('div','overviewContent');content.append(element('div','overviewName',c.title));if(c===active||c===next)content.append(element('div','overviewDescription',c.description||say('Pas de description','No description')));row.append(element('span','overviewNumber',String(c.number)),v,element('time','overviewTime',fmt(c.time)),content);if(c===next)row.append(element('span','overviewBeat'));$('showCueOverviewRows').append(row);}}
const nextRow=document.querySelector('.showOverviewRow.isNext');if(nextRow){nextRow.classList.toggle('isUrgent',urgent);nextRow.querySelector('.overviewBeat').style.opacity=String(beat);}for(const img of document.querySelectorAll('.isActive .overviewVisual img'))img.style.opacity=urgent?String(Math.max(0,remaining/10)):'1';const marks=document.querySelectorAll('#timeline .marker');if(marks.length!==latest.cues.length){marks.forEach(e=>e.remove());for(const c of latest.cues){const m=element('span','marker');m.style.left=(latest.duration?c.time/latest.duration*100:0)+'%';$('timeline').append(m);}}document.querySelectorAll('#timeline .marker').forEach((m,i)=>m.classList.toggle('pastCue',latest.cues[i].time<=t+.0001));}
if(viewer){const params=new URLSearchParams(location.hash.slice(1));(async()=>{relay=params.get('transport')==='relay';if(!relay&&!window.RTCPeerConnection)throw Error(say('Navigateur incompatible avec Copilot.','Browser incompatible with Copilot.'));const id=params.get('session'),key=params.get('key');if(!id||!key)throw Error(say('Scannez le QR de Pilot ou Bridge.','Scan the Pilot or Bridge QR.'));if(relay){session={id,key};await pollRelay();relayTimer=setInterval(pollRelay,500);}else{const p=await request(route('join'),{session:id,key});session={id,peer:p.id,key:p.key};stream();}})().catch(report);setInterval(render,100);}else{const button=$('copilotShareButton');if(button)button.addEventListener('click',async()=>{const d=$('copilotShareDialog');d.showModal();for(const [id,fr,eng] of [['copilotCopy','Copier le lien','Copy link'],['copilotSend','Partager','Share'],['copilotStop','Arrêter le partage','Stop sharing'],['copilotClose','Fermer','Close']])$(id).textContent=say(fr,eng);status(say('Préparation du partage…','Preparing sharing…'));try{const link=await startHost();$('copilotShareLink').value=link;const qr=$('copilotQr');qr.replaceChildren();new QRCode(qr,{text:link,width:512,height:512,correctLevel:QRCode.CorrectLevel.H});const logo=new Image();logo.src='./icons/s2a-copilot-192.png';logo.className='copilotQrLogo';logo.alt='S2A Copilot';qr.append(logo);status(location.protocol==='https:'?(relay?say('Scannez ce QR ou ouvrez le lien sur l’autre appareil. Gardez Pilot ouvert et connecté.','Scan this QR or open the link on the other device. Keep Pilot open and connected.'):say('Scannez le QR dans Safari, sur le même Wi-Fi.','Scan the QR in Safari, on the same Wi-Fi.')):say('Lien local : essai sur ce Mac uniquement. L’iPad nécessite une adresse HTTPS.','Local link: this Mac only. iPad requires an HTTPS address.'));}catch(e){report(e);}});if(button){$('copilotClose').onclick=()=>{$('copilotShareDialog').close();button.focus();};$('copilotShareDialog').onclick=e=>{if(e.target===$('copilotShareDialog'))$('copilotShareDialog').close();};$('copilotStop').onclick=stop;$('copilotCopy').onclick=async()=>{try{if(!shareLink)return;if(navigator.clipboard)await navigator.clipboard.writeText(shareLink);else{$('copilotShareLink').select();if(!document.execCommand('copy'))throw Error();}status(say('Lien copié','Link copied'));}catch(e){status(say('Sélectionnez le lien pour le copier.','Select the link to copy it.'));}};$('copilotSend').onclick=async()=>{if(!shareLink)return;try{if(navigator.share)await navigator.share({title:'S2A Copilot',url:shareLink});else $('copilotCopy').click();}catch(e){if(e.name!=='AbortError')report(e);}};}setInterval(()=>{if(performance.now()-lastSend>=200){lastSend=performance.now();publish();}},100);}
setInterval(()=>{if(viewer&&latest&&performance.now()-lastReceived>2000&&events?.readyState===EventSource.OPEN){events.close();stream();}if(!viewer)for(const [id,p]of peers)if(['failed','disconnected'].includes(p.pc.connectionState)&&events?.readyState===EventSource.OPEN)receive({type:'join',peer:id}).catch(report);},3000);window.addEventListener('pagehide',stop);
})();
