/* Local ES5 onboarding, shared by the full and lightweight applications. */
(function(){'use strict';var trigger=document.getElementById('quickHelpButton');if(!trigger)return;
var overlay=document.createElement('div');overlay.className='quickHelpOverlay';overlay.hidden=true;
var box=document.createElement('section');box.className='quickHelpBox';box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');box.setAttribute('aria-labelledby','quickHelpTitle');
var header=document.createElement('div');header.className='quickHelpHeader';var title=document.createElement('h2');title.id='quickHelpTitle';var close=document.createElement('button');close.type='button';close.className='quickHelpClose';header.appendChild(title);header.appendChild(close);box.appendChild(header);
var counter=document.createElement('p');counter.className='quickHelpCounter';counter.setAttribute('aria-live','polite');var heading=document.createElement('h3');var text=document.createElement('p');text.className='quickHelpText';var image=document.createElement('img');image.className='quickHelpScreenshot';image.width=950;image.height=360;var videoHeading=document.createElement('h3');videoHeading.style.marginTop='24px';var note=document.createElement('p');note.className='quickHelpText';note.style.marginTop='14px';[counter,heading,text,videoHeading,image,note].forEach(function(e){box.appendChild(e);});
var footer=document.createElement('div');footer.className='quickHelpFooter';var previous=document.createElement('button'),next=document.createElement('button'),done=document.createElement('button');previous.type=next.type=done.type='button';next.className=done.className='primary';[previous,next,done].forEach(function(e){footer.appendChild(e);});box.appendChild(footer);overlay.appendChild(box);document.body.appendChild(overlay);
var priorFocus=null,priorOverflow='',opened=false,step=0,seen=false,pendingInstall=null;try{seen=localStorage.getItem('s2a-quick-help-seen')==='1';}catch(e){}
function refresh(){var en=document.documentElement.lang.indexOf('en')===0,light=!!document.getElementById('audioFile'),lang=en?'en':'fr';trigger.setAttribute('aria-label',en?'Help':'Aide');trigger.setAttribute('title',en?'Help':'Aide');trigger.setAttribute('aria-haspopup','dialog');title.textContent=en?'Get started in a minute':'Prise en main en une minute';close.textContent=en?'Close':'Fermer';previous.textContent=en?'Back':'Précédent';next.textContent=en?'Next':'Suivant';done.textContent=en?'Got it':'J’ai compris';counter.textContent=(en?'Step ':'Étape ')+(step+1)+' / 4';
var titles=en?['Create your show','Set up your Cues','Run your show','Save time on your computer']:['Créez votre conduite','Réglez vos Cues','Lancez le spectacle','Gagnez du temps sur ordinateur'];heading.textContent=titles[step];
var body=en?[
 'In Edit, click New and enter the show name. Cue adds an instruction; '+(light?'Music imports your audio file. This lightweight mode plays one track.':'Music / Video imports a file and creates its Cue.'),
 'Enter a title, instructions and, if needed, a visual. Set the Cue time: 02.41 means 2 minutes 41 seconds. '+(light?'Click or drag on the main timeline to change position.':'IN / OUT selects the part of the media to use. Its small Play button previews that file only.'),
 'Switch to Show. Play / Pause controls the whole show. The return icon stops media and goes back to zero. In the Cue list, follow the active Cue highlighted in blue and the countdown in the Timeline panel. The timeline stays at the top while you scroll the Cue list.',
 'On a computer, press the Space bar to play or pause the show, in Edit or Show. When you are typing in a field, Space keeps its usual role.'
 ]:[
 'Dans Edit, cliquez sur Nouveau et donnez un nom au numéro. Cue ajoute une indication ; '+(light?'Musique importe votre fichier audio. Ce mode allégé lit une seule musique.':'Musique / Vidéo importe un fichier et crée sa Cue.'),
 'Renseignez le titre, les consignes et, si besoin, un visuel. Réglez le temps : 02.41 signifie 2 minutes 41 secondes. '+(light?'Touchez ou faites glisser sur la timeline générale pour changer de position.':'IN / OUT délimite la partie du média à jouer. Son petit bouton Lecture prévisualise ce fichier uniquement.'),
 'Passez en Show. Lecture / Pause commande toute la conduite. L’icône de retour arrête les médias et revient à zéro. Dans la liste, suivez la Cue active éclairée en bleu et le décompte dans le panneau Timeline. La timeline reste en haut pendant le défilement de la liste.',
 'Sur ordinateur, appuyez sur la barre Espace pour lancer ou mettre en pause la conduite, en Edit comme en Show. Lorsque vous écrivez dans un champ, Espace conserve son rôle habituel.'
 ];text.textContent=body[step];videoHeading.textContent=en?'Muted video':'Vidéo muette';videoHeading.hidden=step!==3;var prefix=light?'../':'';image.onerror=function(){var key=(light?'legacy-':'')+lang+'-'+['create','cue','show','mute'][step]+'.png';var data=window.S2AHelpImages&&window.S2AHelpImages[key];if(data&&image.src!==data)image.src=data;};image.src=prefix+'assets/help/'+(light?'legacy-':'')+lang+'-'+['create','cue','show','mute'][step]+'.png?v=1.4.97';image.alt=(en?'Screenshot: ':'Capture : ')+titles[step];image.hidden=step===3&&light;
note.textContent=step===3?(en?(light?'Video Cues are unavailable in lightweight mode.':'In Edit, open a video Cue and click its speaker button to mute or restore the video audio. The crossed-out speaker means the video is muted.'):(light?'Les Cues vidéo sont indisponibles en mode allégé.':'Dans Edit, déroulez une Cue vidéo et cliquez sur son bouton haut-parleur pour couper ou réactiver le son. Le haut-parleur barré indique que la vidéo est muette.')):'';note.hidden=step!==3;previous.disabled=step===0;next.hidden=step===3;done.hidden=step!==3;}
function hide(){if(!opened)return;opened=false;seen=true;try{localStorage.setItem('s2a-quick-help-seen','1');}catch(e){}overlay.hidden=true;document.body.style.overflow=priorOverflow;trigger.setAttribute('aria-expanded','false');if(priorFocus&&priorFocus!==document.body&&document.documentElement.contains(priorFocus))priorFocus.focus();else trigger.focus();var install=pendingInstall;pendingInstall=null;if(install)setTimeout(install,150);}
function show(){if(opened)return;if(window.S2AStartup&&window.S2AStartup.defer(show))return;step=0;refresh();priorFocus=document.activeElement;priorOverflow=document.body.style.overflow;opened=true;overlay.hidden=false;document.body.style.overflow='hidden';trigger.setAttribute('aria-expanded','true');close.focus();}
trigger.onclick=show;close.onclick=hide;done.onclick=hide;previous.onclick=function(){step=Math.max(0,step-1);refresh();next.focus();};next.onclick=function(){step=Math.min(3,step+1);refresh();(step===3?done:next).focus();};overlay.onclick=function(e){if(e.target===overlay)hide();};
document.addEventListener('keydown',function(e){if(!opened)return;if(e.keyCode===27||e.key==='Escape'){e.preventDefault();hide();}else if(e.keyCode===9||e.key==='Tab'){var last=step===3?done:next;if(e.shiftKey&&document.activeElement===close){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();close.focus();}}else if((e.keyCode===32||e.key===' ')&&e.target.tagName!=='BUTTON'){e.preventDefault();}e.stopPropagation();},true);
window.S2AQuickHelp={start:function(){refresh();if(!seen)show();},open:show,isOpen:function(){return opened;},deferInstall:function(callback){if(!seen||opened){pendingInstall=callback;return true;}return false;}};
window.addEventListener('s2a-language-change',refresh);var selector=document.getElementById('lang');if(selector)selector.addEventListener('change',refresh);trigger.setAttribute('aria-expanded','false');refresh();if(selector)window.S2AQuickHelp.start();
})();
