/* Local ES5 onboarding, shared by the full and lightweight applications. */
(function(){'use strict';var trigger=document.getElementById('quickHelpButton');if(!trigger)return;
var overlay=document.createElement('div');overlay.className='quickHelpOverlay';overlay.hidden=true;
var box=document.createElement('section');box.className='quickHelpBox';box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');box.setAttribute('aria-labelledby','quickHelpTitle');
var header=document.createElement('div');header.className='quickHelpHeader';var title=document.createElement('h2');title.id='quickHelpTitle';var close=document.createElement('button');close.type='button';close.className='quickHelpClose';header.appendChild(title);header.appendChild(close);box.appendChild(header);
var counter=document.createElement('p');counter.className='quickHelpCounter';counter.setAttribute('aria-live','polite');var heading=document.createElement('h3');var text=document.createElement('p');text.className='quickHelpText';var image=document.createElement('img');image.className='quickHelpScreenshot';image.width=950;image.height=360;var note=document.createElement('p');note.className='quickHelpNote';[counter,heading,text,image,note].forEach(function(e){box.appendChild(e);});
var footer=document.createElement('div');footer.className='quickHelpFooter';var previous=document.createElement('button'),next=document.createElement('button'),done=document.createElement('button');previous.type=next.type=done.type='button';next.className=done.className='primary';[previous,next,done].forEach(function(e){footer.appendChild(e);});box.appendChild(footer);overlay.appendChild(box);document.body.appendChild(overlay);
var priorFocus=null,priorOverflow='',opened=false,step=0,seen=false,pendingInstall=null;try{seen=localStorage.getItem('s2a-quick-help-seen')==='1';}catch(e){}
function refresh(){var en=document.documentElement.lang.indexOf('en')===0,light=!!document.getElementById('audioFile'),lang=en?'en':'fr';trigger.setAttribute('aria-label',en?'Help':'Aide');trigger.setAttribute('title',en?'Help':'Aide');trigger.setAttribute('aria-haspopup','dialog');title.textContent=en?'Get started in a minute':'Prise en main en une minute';close.textContent=en?'Close':'Fermer';previous.textContent=en?'Back':'Précédent';next.textContent=en?'Next':'Suivant';done.textContent=en?'Got it':'J’ai compris';counter.textContent=(en?'Step ':'Étape ')+(step+1)+' / 3';
var titles=en?['Create your show','Set up your Cues','Run your show']:['Créez votre conduite','Réglez vos Cues','Lancez le spectacle'];heading.textContent=titles[step];
var body=en?[
 'In Edit, click New and enter the show name. Cue adds an instruction; '+(light?'Music imports your audio file. This lightweight mode plays one track.':'Music / Video imports a file and creates its Cue.'),
 'Enter a title, instructions and, if needed, a visual. Set the Cue time: 02.41 means 2 minutes 41 seconds. '+(light?'Click or drag on the main timeline to change position.':'IN / OUT selects the part of the media to use. Its small Play button previews that file only.'),
 'Switch to Show. Play / Pause controls the whole show. The return icon stops media and goes back to zero. Follow the active Cue and the next countdown.'
 ]:[
 'Dans Edit, cliquez sur Nouveau et donnez un nom au numéro. Cue ajoute une indication ; '+(light?'Musique importe votre fichier audio. Ce mode allégé lit une seule musique.':'Musique / Vidéo importe un fichier et crée sa Cue.'),
 'Renseignez le titre, les consignes et, si besoin, un visuel. Réglez le temps : 02.41 signifie 2 minutes 41 secondes. '+(light?'Touchez ou faites glisser sur la timeline générale pour changer de position.':'IN / OUT délimite la partie du média à jouer. Son petit bouton Lecture prévisualise ce fichier uniquement.'),
 'Passez en Show. Lecture / Pause commande toute la conduite. L’icône de retour arrête les médias et revient à zéro. Suivez la Cue active et le décompte de la prochaine.'
 ];text.textContent=body[step];var prefix=light?'../':'';image.src=prefix+'assets/help/'+(light?'legacy-':'')+lang+'-'+['create','cue','show'][step]+'.png';image.alt=(en?'Screenshot: ':'Capture : ')+titles[step];
note.textContent=step===2?(en?(light?'Changes are saved locally. Export project keeps a portable copy; Printable cue sheet prepares your technician’s instructions.':'Changes are saved locally. Save as… keeps a portable copy with your media; Cue sheet PDF prepares your technician’s instructions.'):(light?'Les modifications sont sauvegardées localement. Exporter le projet garde une copie transportable ; Conduite imprimable prépare les consignes du technicien.':'Les modifications sont sauvegardées localement. Enregistrer sous… garde une copie transportable avec les médias ; Conduite PDF prépare les consignes du technicien.')):'';note.hidden=step!==2;previous.disabled=step===0;next.hidden=step===2;done.hidden=step!==2;}
function hide(){if(!opened)return;opened=false;seen=true;try{localStorage.setItem('s2a-quick-help-seen','1');}catch(e){}overlay.hidden=true;document.body.style.overflow=priorOverflow;trigger.setAttribute('aria-expanded','false');if(priorFocus&&priorFocus!==document.body&&document.documentElement.contains(priorFocus))priorFocus.focus();else trigger.focus();var install=pendingInstall;pendingInstall=null;if(install)setTimeout(install,150);}
function show(){if(opened)return;step=0;refresh();priorFocus=document.activeElement;priorOverflow=document.body.style.overflow;opened=true;overlay.hidden=false;document.body.style.overflow='hidden';trigger.setAttribute('aria-expanded','true');close.focus();}
trigger.onclick=show;close.onclick=hide;done.onclick=hide;previous.onclick=function(){step=Math.max(0,step-1);refresh();next.focus();};next.onclick=function(){step=Math.min(2,step+1);refresh();(step===2?done:next).focus();};overlay.onclick=function(e){if(e.target===overlay)hide();};
document.addEventListener('keydown',function(e){if(!opened)return;if(e.keyCode===27||e.key==='Escape'){e.preventDefault();hide();}else if(e.keyCode===9||e.key==='Tab'){var last=step===2?done:next;if(e.shiftKey&&document.activeElement===close){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();close.focus();}}else if((e.keyCode===32||e.key===' ')&&e.target.tagName!=='BUTTON'){e.preventDefault();}e.stopPropagation();},true);
window.S2AQuickHelp={start:function(){refresh();if(!seen)show();},open:show,isOpen:function(){return opened;},deferInstall:function(callback){if(!seen||opened){pendingInstall=callback;return true;}return false;}};
window.addEventListener('s2a-language-change',refresh);var selector=document.getElementById('lang');if(selector)selector.addEventListener('change',refresh);trigger.setAttribute('aria-expanded','false');refresh();if(selector)window.S2AQuickHelp.start();
})();
