/* Metadata-only RTCDataChannel. Pilot is authoritative; receivers have no controls. */
(function(){'use strict';
var isHost=document.body.dataset.role==='host',status=document.getElementById('status'),display=document.getElementById('display'),peers=new Map(),session,events,latest=null,receivedAt=0,revision=0,position=0,playing=false,epoch=performance.now(),lastSend=0,signalQueue=Promise.resolve();
var cues=[{number:1,time:0,title:'Ouverture du rideau',description:'Ouvrir le rideau. Monter les faces à 60 %.'},{number:2,time:20,title:'Entrée de l’artiste',description:'Suivre l’artiste à la poursuite. Attendre son salut.'},{number:3,time:45,title:'Ambiance bleue',description:'Passer les latéraux au bleu. Couper les faces en fondu.'},{number:4,time:70,title:'Changement de tableau',description:'Préparer les accessoires à cour. Attendre le top du régisseur.'},{number:5,time:100,title:'Salut final',description:'Plein feu. Ouvrir le rideau et accompagner les saluts.'},{number:6,time:120,title:'Noir salle',description:''}];
function endpoint(route){return '/api/'+route+'?session='+session.id+'&key='+session.key+(session.peer?'&peer='+session.peer:'');}
async function request(url,data){var response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data||{})});var result=await response.json();if(!response.ok)throw Error(result.error||'Signalisation indisponible');return result;}
function now(){return playing?Math.min(130,position+(performance.now()-epoch)/1000):position;}
function state(){var t=now(),index=-1;cues.forEach(function(c,i){if(c.time<=t)index=i;});return {type:'state',version:1,revision:revision,time:t,playing:playing,active:cues[index]||null,next:cues[index+1]||null,after:cues.slice(index+2)};}
function validCue(c){return c===null||(c&&Number.isInteger(c.number)&&c.number>0&&Number.isFinite(c.time)&&typeof c.title==='string'&&c.title.length<=300&&typeof c.description==='string'&&c.description.length<=4000);}
function validState(s){return s&&s.type==='state'&&s.version===1&&Number.isInteger(s.revision)&&Number.isFinite(s.time)&&s.time>=0&&typeof s.playing==='boolean'&&validCue(s.active)&&validCue(s.next)&&Array.isArray(s.after)&&s.after.length<=1000&&s.after.every(validCue);}
function text(tag,value,cls){var el=document.createElement(tag);el.textContent=value;if(cls)el.className=cls;return el;}
var renderKey='';function render(s,t,stale){var key=JSON.stringify([s.active,s.next,s.after]);if(key!==renderKey){renderKey=key;display.textContent='';var active=text('section','','card active');active.append(text('h2','CUE ACTIVE'+(s.active?' · '+s.active.number:'')),text('h3',s.active?s.active.title:'Aucune Cue'));if(s.active&&s.active.description)active.append(text('p',s.active.description));display.append(active);var next=text('section','','card next');next.append(text('h2','PROCHAINE CUE'+(s.next?' · '+s.next.number:'')),text('h3',s.next?s.next.title:'Fin de conduite'),text('div','--:--','countdown'));if(s.next)next.append(text('p',s.next.description||'Pas de description'));display.append(next);var after=text('section','','card after'),list=document.createElement('ul');after.append(text('h2','ENSUITE'));s.after.forEach(function(c){list.append(text('li',c.number+' · '+c.title));});if(!s.after.length)after.append(text('p','Aucune autre Cue'));else after.append(list);display.append(after);}
 var nextBox=display.querySelector('.next'),remaining=s.next?Math.max(0,s.next.time-t):null;nextBox.classList.toggle('urgent',remaining!==null&&remaining<=10&&!stale);nextBox.querySelector('.countdown').textContent=stale||remaining===null?'--:--':format(Math.ceil(remaining));
}
function format(t){return String(Math.floor(t/60)).padStart(2,'0')+':'+String(Math.floor(t%60)).padStart(2,'0');}
function connectedCount(){if(!isHost)return;var count=Array.from(peers.values()).filter(function(p){return p.channel&&p.channel.readyState==='open';}).length;document.getElementById('peers').textContent=count+' compagnon'+(count>1?'s':'')+' connecté'+(count>1?'s':'');}
function discard(id){var p=peers.get(id);if(p){p.pc.close();peers.delete(id);}connectedCount();}
function makePeer(id){discard(id);var pc=new RTCPeerConnection({iceServers:[]}),p={pc:pc,channel:null,pending:[]};peers.set(id,p);pc.onicecandidate=function(e){if(e.candidate&&peers.get(id)===p)signal('ice',e.candidate.toJSON(),id).catch(showError);};pc.onconnectionstatechange=connectedCount;pc.oniceconnectionstatechange=connectedCount;
 function attach(channel){p.channel=channel;channel.onopen=function(){connectedCount();if(isHost)channel.send(JSON.stringify(state()));};channel.onclose=connectedCount;
 // Host deliberately never installs a message handler: no incoming transport commands.
 if(!isHost)channel.onmessage=function(e){if(typeof e.data!=='string'||e.data.length>64000)return;try{var value=JSON.parse(e.data);if(!validState(value)||(latest&&value.revision<latest.revision))return;latest=value;receivedAt=performance.now();status.textContent='Connecté à Pilot · Lecture seule';status.classList.remove('stale');}catch(ignore){}};
 }
 if(isHost)attach(pc.createDataChannel('s2a-show',{ordered:true}));else pc.ondatachannel=function(e){attach(e.channel);};return p;
}
function signal(type,value,id){return request(endpoint('signal'),{type:type,value:value,peer:id});}
async function receive(message){var p;if(message.type==='join'&&isHost){p=makePeer(message.peer);await p.pc.setLocalDescription(await p.pc.createOffer());await signal('offer',p.pc.localDescription.toJSON(),message.peer);return;}
 var id=isHost?message.peer:'host';p=peers.get(id);
 if(message.type==='offer'&&!isHost){p=makePeer(id);await p.pc.setRemoteDescription(message.value);while(p.pending.length)await p.pc.addIceCandidate(p.pending.shift());await p.pc.setLocalDescription(await p.pc.createAnswer());await signal('answer',p.pc.localDescription.toJSON());}
 else if(message.type==='answer'&&isHost&&p){await p.pc.setRemoteDescription(message.value);while(p.pending.length)await p.pc.addIceCandidate(p.pending.shift());}
 else if(message.type==='ice'&&p){if(p.pc.remoteDescription)await p.pc.addIceCandidate(message.value);else p.pending.push(message.value);}
}
function showError(error){status.textContent=error.message||'Connexion interrompue';status.classList.add('stale');}
function stream(){events=new EventSource(endpoint('events'));events.onmessage=function(e){signalQueue=signalQueue.then(function(){return receive(JSON.parse(e.data));}).catch(showError);};events.onopen=function(){if(isHost){status.textContent='Appairage disponible sur le réseau local';status.classList.remove('stale');}};events.onerror=function(){if(isHost)showError(Error('Signalisation indisponible · les connexions WebRTC existantes peuvent continuer'));};}
async function start(){if(!window.RTCPeerConnection)throw Error('WebRTC indisponible dans ce navigateur.');if(isHost){var data=await request('/api/sessions');session={id:data.id,key:data.hostKey};var link=location.origin+'/copilot#session='+data.id+'&key='+data.viewKey;document.getElementById('pairLink').textContent=link;document.getElementById('pairLink').href=link;new QRCode(document.getElementById('qr'),{text:link,width:200,height:200,correctLevel:QRCode.CorrectLevel.M});
 document.getElementById('play').onclick=function(){position=now();playing=!playing;epoch=performance.now();revision++;};document.getElementById('next').onclick=function(){var next=cues.find(function(c){return c.time>now()+.01;});if(next){position=next.time;epoch=performance.now();revision++;}};document.getElementById('reset').onclick=function(){position=0;playing=false;epoch=performance.now();revision++;};
 }else{var params=new URLSearchParams(location.hash.slice(1)),id=params.get('session'),key=params.get('key');if(!id||!key)throw Error('Scannez le QR code de S2A Pilot TEST.');var peer=await request('/api/join',{session:id,key:key});session={id:id,peer:peer.id,key:peer.key};}stream();}
setInterval(function(){if(isHost){var s=state();render(s,s.time,false);document.getElementById('time').textContent='Conduite '+format(s.time);if(performance.now()-lastSend>=200){lastSend=performance.now();peers.forEach(function(p){if(p.channel&&p.channel.readyState==='open'&&p.channel.bufferedAmount<64000)p.channel.send(JSON.stringify(s));});}}
 else if(latest){var age=(performance.now()-receivedAt)/1000,stale=age>2;render(latest,latest.time+(latest.playing&&!stale?age:0),stale);if(stale){status.textContent='Connexion interrompue · informations figées';status.classList.add('stale');}}},100);
// A dead peer is rebuilt through the local signaler. No Internet/STUN/TURN dependency.
setInterval(function(){if(!isHost&&latest&&performance.now()-receivedAt>2000&&events&&events.readyState===EventSource.OPEN){events.close();stream();}if(isHost){peers.forEach(function(p,id){if((['failed','disconnected'].includes(p.pc.connectionState||p.pc.iceConnectionState)||(p.channel&&p.channel.readyState==='closed'))&&events.readyState===EventSource.OPEN)receive({type:'join',peer:id}).catch(showError);});}},3000);
window.addEventListener('pagehide',function(){if(events)events.close();peers.forEach(function(p){p.pc.close();});});start().catch(showError);
})();
