const{chromium,webkit}=require(process.env.S2A_PLAYWRIGHT||'playwright'),a=require('assert/strict');
(async()=>{const chrome=await chromium.launch({...(process.env.S2A_CHROME?{executablePath:process.env.S2A_CHROME}:{}),headless:true}),wk=await webkit.launch({headless:true}),hc=await chrome.newContext(),vc1=await chrome.newContext(),vc2=await wk.newContext(),host=await hc.newPage(),v1=await vc1.newPage(),v2=await vc2.newPage(),errors=[];for(const p of[host,v1,v2]){await p.addInitScript(()=>{const Original=window.RTCPeerConnection;window.__testPeers=[];window.RTCPeerConnection=class extends Original{constructor(...args){super(...args);window.__testPeers.push(this)}}});p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());}await host.goto('http://127.0.0.1:8098');await host.waitForFunction(()=>document.getElementById('pairLink').href.includes('#session='));const link=await host.locator('#pairLink').getAttribute('href');await Promise.all([v1.goto(link),v2.goto(link)]);for(const v of[v1,v2]){await v.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Connecté'),null,{timeout:15000});a.equal(await v.locator('button,input,select,video,audio,canvas').count(),0);a.equal(await v.locator('.active h3').innerText(),'Ouverture du rideau');}await host.waitForFunction(()=>document.getElementById('peers').textContent.includes('2 compagnons'));
for(const title of ['Entrée de l’artiste','Ambiance bleue','Changement de tableau']){await host.locator('#next').click();for(const v of[v1,v2])await v.waitForFunction(t=>document.querySelector('.active h3')?.textContent===t,title)}
// Existing data channels must continue even when the local signaler is temporarily unreachable.
await host.route('**/api/**',route=>route.abort());await v1.route('**/api/**',route=>route.abort());await v2.route('**/api/**',route=>route.abort());await host.locator('#next').click();for(const v of[v1,v2])await v.waitForFunction(()=>document.querySelector('.active h3')?.textContent==='Salut final');await host.unroute('**/api/**');await v1.unroute('**/api/**');await v2.unroute('**/api/**');await host.locator('#reset').click();for(const v of[v1,v2])await v.waitForFunction(()=>document.querySelector('.active h3')?.textContent==='Ouverture du rideau');
await host.locator('#play').click();await v1.waitForTimeout(1100);const countdown=await v1.locator('.countdown').innerText();a(countdown==='00:18'||countdown==='00:19'||countdown==='00:20');
// Browser offline cuts the viewer network: stale UI must stop claiming a live countdown.
await vc1.setOffline(true);await v1.evaluate(()=>window.__testPeers.forEach(pc=>pc.close()));await v1.waitForTimeout(3500);a(await v1.locator('#status').innerText().then(t=>t.includes('interrompue')));a.equal(await v1.locator('.countdown').innerText(),'--:--');await vc1.setOffline(false);await v1.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Connecté'),null,{timeout:15000});
await v2.reload();await v2.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Connecté'),null,{timeout:15000});await host.locator('#reset').click();for(const v of[v1,v2])await v.waitForFunction(()=>document.querySelector('.active h3')?.textContent==='Ouverture du rideau');a.deepEqual(errors,[]);await host.screenshot({path:require('path').join(require('os').tmpdir(),'s2a-copilot-host.png'),fullPage:true});await v1.screenshot({path:require('path').join(require('os').tmpdir(),'s2a-copilot-viewer.png'),fullPage:true});console.log('PASS local signaling; Chrome + WebKit receivers; two receivers; three Cue changes; countdown; read-only; network loss/stale/reconnect; viewer reload; all external requests blocked');await chrome.close();await wk.close()})().catch(e=>{console.error(e);process.exit(1)});
