/* Local adapters for Safari 9. No runtime transpilation or remote dependencies. */
(function(w){'use strict';
var api=w.S2ACompat={},EP=Element.prototype;
// Safari 9 treats an options object as capture=true; normalize it and implement once.
var supportsOptions=false;try{var probe=Object.defineProperty({},'capture',{get:function(){supportsOptions=true;return false;}});var noop=function(){};w.addEventListener('s2a-options',noop,probe);w.removeEventListener('s2a-options',noop,probe);}catch(e){}
if(!supportsOptions){var prototypes=w.EventTarget?[w.EventTarget.prototype]:[Node.prototype,Window.prototype],add=document.addEventListener,remove=document.removeEventListener,records=new WeakMap();var addListener=function(type,fn,options){var capture=!!(typeof options==='object'?options&&options.capture:options),once=!!(options&&typeof options==='object'&&options.once),self=this;if(!once)return add.call(this,type,fn,capture);var list=records.get(this)||[];for(var i=0;i<list.length;i++)if(list[i].type===type&&list[i].fn===fn&&list[i].capture===capture)return;var rec={type:type,fn:fn,capture:capture};rec.wrap=function(e){self.removeEventListener(type,fn,capture);if(typeof fn==='function')fn.call(self,e);else fn.handleEvent(e);};list.push(rec);records.set(this,list);return add.call(this,type,rec.wrap,capture);};var removeListener=function(type,fn,options){var capture=!!(typeof options==='object'?options&&options.capture:options),list=records.get(this)||[];for(var i=list.length-1;i>=0;i--)if(list[i].type===type&&list[i].fn===fn&&list[i].capture===capture){remove.call(this,type,list[i].wrap,capture);list.splice(i,1);}return remove.call(this,type,fn,capture);};prototypes.forEach(function(p){p.addEventListener=addListener;p.removeEventListener=removeListener;});}

try{new Event('s2a-probe');}catch(e){w.Event=function(type,opts){var ev=document.createEvent('Event');opts=opts||{};ev.initEvent(type,!!opts.bubbles,!!opts.cancelable);return ev;};}
if(!w.AbortSignal)w.AbortSignal={};
if(!w.crypto)w.crypto={};
if(!EP.matches)EP.matches=EP.webkitMatchesSelector;
if(!EP.closest)EP.closest=function(s){var e=this;while(e&&e.nodeType===1){if(e.matches(s))return e;e=e.parentElement;}return null;};
function append(){for(var i=0;i<arguments.length;i++)this.appendChild(typeof arguments[i]==='string'?document.createTextNode(arguments[i]):arguments[i]);}
function prepend(){var fragment=document.createDocumentFragment();append.apply(fragment,arguments);this.insertBefore(fragment,this.firstChild);}
[EP,DocumentFragment.prototype,Document.prototype].forEach(function(p){if(!p.append)p.append=append;if(!p.prepend)p.prepend=prepend;if(!p.replaceChildren)p.replaceChildren=function(){while(this.firstChild)this.removeChild(this.firstChild);append.apply(this,arguments);};});
if(!EP.remove)EP.remove=function(){if(this.parentNode)this.parentNode.removeChild(this);};
if(!EP.replaceWith)EP.replaceWith=function(el){if(this.parentNode)this.parentNode.replaceChild(el,this);};
if(!('isConnected' in EP))Object.defineProperty(EP,'isConnected',{get:function(){return document.documentElement.contains(this);}});
if(!w.TextEncoder)w.TextEncoder=function(){};
if(!TextEncoder.prototype.encode)TextEncoder.prototype.encode=function(text){var s=unescape(encodeURIComponent(text)),b=new Uint8Array(s.length);for(var i=0;i<s.length;i++)b[i]=s.charCodeAt(i);return b;};
if(!w.TextDecoder){w.TextDecoder=function(enc){this.encoding=enc||'utf-8';};TextDecoder.prototype.decode=function(input){var b=input instanceof ArrayBuffer?new Uint8Array(input):input,s='',cp=[8364,129,8218,402,8222,8230,8224,8225,710,8240,352,8249,338,141,381,143,144,8216,8217,8220,8221,8226,8211,8212,732,8482,353,8250,339,157,382,376];for(var i=0;i<b.length;i++)s+=String.fromCharCode(this.encoding==='windows-1252'&&b[i]>=128&&b[i]<160?cp[b[i]-128]:b[i]);return this.encoding==='windows-1252'?s:decodeURIComponent(escape(s));};}
function read(blob,kind){return new Promise(function(resolve,reject){var r=new FileReader();r.onload=function(){resolve(r.result);};r.onerror=function(){reject(r.error||Error('File read failed'));};r['readAs'+kind](blob);});}
if(!Blob.prototype.arrayBuffer)Blob.prototype.arrayBuffer=function(){return read(this,'ArrayBuffer');};
if(!Blob.prototype.text)Blob.prototype.text=function(){return read(this,'Text');};
try{new File([''],'test');}catch(e){w.File=function(parts,name,opts){var b=new Blob(parts,opts||{});b.name=name;b.lastModified=opts&&opts.lastModified||Date.now();return b;};}
if(!w.ResizeObserver){w.ResizeObserver=function(cb){var self=this;this.targets=[];this.frame=0;this.notify=function(){if(self.frame)return;self.frame=requestAnimationFrame(function(){self.frame=0;if(self.targets.length)cb(self.targets.map(function(t){return{target:t,contentRect:t.getBoundingClientRect()};}),self);});};w.addEventListener('resize',this.notify);};ResizeObserver.prototype.observe=function(t){this.targets.push(t);this.notify();};ResizeObserver.prototype.disconnect=function(){this.targets=[];w.removeEventListener('resize',this.notify);cancelAnimationFrame(this.frame);};}
var AC=w.AudioContext||w.webkitAudioContext;
if(AC){var decode=AC.prototype.decodeAudioData;AC.prototype.decodeAudioData=function(data,success,failure){var self=this;return new Promise(function(resolve,reject){function ok(v){if(success)success(v);resolve(v);}function bad(e){if(failure)failure(e);reject(e);}try{var result=decode.call(self,data,ok,bad);if(result&&result.then)result.then(ok,bad);}catch(e){bad(e);}});};}
var decoderContext=null;api.decoderContext=function(){if(!decoderContext)decoderContext=new AC();return decoderContext;};
api.unlock=function(context){if(!context)return;try{var source=context.createBufferSource();source.buffer=context.createBuffer(1,1,22050);source.connect(context.destination);source.start(0);}catch(e){}};
var nativePlay=HTMLMediaElement.prototype.play;
HTMLMediaElement.prototype.play=function(){var el=this,result=nativePlay.call(el);if(result&&result.then)return result;return new Promise(function(resolve,reject){var timer;function done(error){clearTimeout(timer);el.removeEventListener('playing',ok);el.removeEventListener('error',bad);error?reject(error):resolve();}function ok(){done();}function bad(){done(Error('Media playback failed'));}if(!el.paused){resolve();return;}el.addEventListener('playing',ok);el.addEventListener('error',bad);timer=setTimeout(function(){el.paused?bad():ok();},5000);});};
// iOS does not honor HTMLMediaElement.volume: apply existing fades through Web Audio.
var gains=new WeakMap();
api.setMediaGain=function(el,value,context){var rec=gains.get(el);if(!rec&&context&&context.createMediaElementSource){try{rec={source:context.createMediaElementSource(el),gain:context.createGain()};rec.source.connect(rec.gain);rec.gain.connect(context.destination);gains.set(el,rec);}catch(e){rec=null;}}if(rec)rec.gain.gain.value=Math.max(0,Math.min(1,value));else try{el.volume=Math.max(0,Math.min(1,value));}catch(e){}};
// Synthesize pointer events from touch/mouse; only cancel gestures consumed by the app.
if(!w.PointerEvent){var captures={},touchTargets={},lastTouch=0;
EP.setPointerCapture=function(id){captures[id]=this;};EP.releasePointerCapture=function(id){delete captures[id];};EP.hasPointerCapture=function(id){return captures[id]===this;};
function send(type,target,x,y,id,kind,buttons){if(!target)return true;var ev=document.createEvent('MouseEvents');ev.initMouseEvent(type,true,true,w,0,x,y,x,y,false,false,false,false,0,null);[['pointerId',id],['pointerType',kind],['isPrimary',true],['buttons',buttons]].forEach(function(p){Object.defineProperty(ev,p[0],{value:p[1]});});return target.dispatchEvent(ev);}
['touchstart','touchmove','touchend','touchcancel'].forEach(function(type){document.addEventListener(type,function(e){lastTouch=Date.now();var prevented=false;for(var i=0;i<e.changedTouches.length;i++){var t=e.changedTouches[i],id=t.identifier+2;if(type==='touchstart')touchTargets[id]=t.target;var target=captures[id]||touchTargets[id]||t.target;var p=type==='touchstart'?'pointerdown':type==='touchmove'?'pointermove':type==='touchend'?'pointerup':'pointercancel';if(!send(p,target,t.clientX,t.clientY,id,'touch',p==='pointerup'?0:1))prevented=true;if(type==='touchend'||type==='touchcancel'){delete captures[id];delete touchTargets[id];}}if(prevented)e.preventDefault();},false);});
['mousedown','mousemove','mouseup'].forEach(function(type){document.addEventListener(type,function(e){if(Date.now()-lastTouch<700)return;var target=captures[1]||e.target,p=type==='mousedown'?'pointerdown':type==='mousemove'?'pointermove':'pointerup';if(!send(p,target,e.clientX,e.clientY,1,'mouse',type==='mouseup'?0:e.buttons||1))e.preventDefault();if(type==='mouseup')delete captures[1];},false);});
}
// Older Safari treats audio/* as a photo/video request. Keep the document picker unrestricted.
['globalMediaFile','projectFile'].forEach(function(id){var el=document.getElementById(id);if(el)el.removeAttribute('accept');});
// Read the previous lightweight draft without deleting or overwriting it.
api.legacyProject=function(){return new Promise(function(resolve){var req=indexedDB.open('s2a-pilot-legacy',1);req.onupgradeneeded=function(){req.transaction.abort();};req.onerror=function(){resolve(null);};req.onsuccess=function(){var db=req.result;if(!db.objectStoreNames.contains('draft')){db.close();resolve(null);return;}var get=db.transaction('draft','readonly').objectStore('draft').get('current');get.onsuccess=function(){db.close();resolve(get.result||null);};get.onerror=function(){db.close();resolve(null);};};});};
api.exportWindow=null;var save=document.getElementById('saveAsBtn');if(save)save.addEventListener('click',function(){if(!('download' in document.createElement('a')))api.exportWindow=w.open('about:blank','_blank');},true);
api.download=function(blob,name){var url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;if('download' in a){document.body.appendChild(a);a.click();a.remove();}else{var target=api.exportWindow;// Read the previous lightweight draft without deleting or overwriting it.
api.legacyProject=function(){return new Promise(function(resolve){var req=indexedDB.open('s2a-pilot-legacy',1);req.onupgradeneeded=function(){req.transaction.abort();};req.onerror=function(){resolve(null);};req.onsuccess=function(){var db=req.result;if(!db.objectStoreNames.contains('draft')){db.close();resolve(null);return;}var get=db.transaction('draft','readonly').objectStore('draft').get('current');get.onsuccess=function(){db.close();resolve(get.result||null);};get.onerror=function(){db.close();resolve(null);};};});};
api.exportWindow=null;if(target&&!target.closed)target.location.href=url;else w.open(url,'_blank');}setTimeout(function(){URL.revokeObjectURL(url);},60000);};
})(window);
