(function(){'use strict';
var labelKey='';
var byId=function(id){return document.getElementById(id);},lang='fr',db=null,saveTimer=0,project={title:'',cues:[],audio:null},time=0,playing=false,epoch=0,base=0,show=false,imageTarget=null,audio=byId('audio'),dragging=false,hasChanges=false,audioAttempted=false;
try{lang=localStorage.getItem('s2a-language')||((navigator.language||'en').indexOf('fr')===0?'fr':'en');}catch(e){}
var dictionary={modeName:['Compatibilité ancien navigateur','Older-browser compatibility'],notice:['Mode allégé : une musique, Cues, visuels, sauvegarde locale et export de projet. Vidéo, waveform, mixage, édition IN/OUT et sortie étendue indisponibles. La conduite imprimable remplace l’aperçu PDF intégré. Le fonctionnement sur l’iPad réel reste à vérifier.','Lightweight mode: one music track, Cues, visuals, local save and project export. Video, waveform, mixing, IN/OUT editing and extended output unavailable. A printable cue sheet replaces the built-in PDF preview. Physical-device validation is still required.'],new:['Nouveau','New'],open:['Ouvrir','Open'],export:['Exporter le projet','Export project'],print:['Conduite imprimable','Printable cue sheet'],add:['Cue','Cue'],music:['Musique','Music'],video:['Vidéo indisponible','Video unavailable'],output:['Sortie vidéo indisponible','Video output unavailable'],activeLabel:['CUE ACTIVE','ACTIVE CUE'],nextLabel:['PROCHAINE CUE','NEXT CUE']};
function tr(fr,en){return lang==='en'?en:fr;}
function fmt(t){t=Math.max(0,t);return ('0'+Math.floor(t/60)).slice(-2)+':'+('0'+Math.floor(t%60)).slice(-2)+'.'+Math.floor(t*10%10);}
function displayTime(t,countdown){if(!show)return fmt(t);t=Math.max(0,t);t=countdown?Math.ceil(t):Math.floor(t);return ('0'+Math.floor(t/60)).slice(-2)+':'+('0'+t%60).slice(-2);}
function parse(s){var m=String(s).trim().match(/^(\d+)[.:,](\d{1,2})(?:[.,](\d+))?$/);return m?Number(m[1])*60+Number(m[2])+Number('0.'+(m[3]||0)):Number(s);}
function ordered(){return project.cues.slice().sort(function(a,b){return a.time-b.time;});}
function duration(){var a=project.audio,c=ordered();return Math.max(10,c.length?c[c.length-1].time+10:0,a?a.start+a.duration:0);}
function now(){return playing?Math.min(duration(),base+(Date.now()-epoch)/1000):time;}
function pause(){time=now();playing=false;audio.pause();}
function syncAudio(){var a=project.audio;audioAttempted=false;if(!a)return;var p=time-a.start;try{audio.currentTime=(a.inPoint||0)+Math.max(0,Math.min(a.duration,p));}catch(e){}if(playing&&p>=0&&p<a.duration){audioAttempted=true;var result=audio.play();if(result&&result.catch)result.catch(function(){pause();byId('saveStatus').textContent=tr('Lecture audio refusée : appuyez de nouveau sur Lecture.','Audio playback denied: press Play again.');});}else audio.pause();}
function play(){base=time;epoch=Date.now();playing=true;syncAudio();}
function seek(t){var was=playing;pause();time=Math.max(0,Math.min(duration(),t));syncAudio();if(was)play();paint();}
function paint(){var t=now(),d=duration(),c=ordered(),active=null,next=null;for(var i=0;i<c.length;i++){if(c[i].time<=t)active=c[i];else{next=c[i];break;}}byId('clock').textContent=displayTime(t)+' / '+displayTime(d);byId('head').style.left=(t/d*100)+'%';S2AMaterial.button(byId('play'),playing?'pause':'play_arrow',playing?tr('Ⅱ Pause','Ⅱ Pause'):tr('▶ Lecture','▶ Play'));byId('activeTitle').textContent=active?(c.indexOf(active)+1)+' — '+active.name:tr('Aucune Cue','No Cue');byId('activeDesc').textContent=active?active.description:'';byId('nextTitle').textContent=next?(c.indexOf(next)+1)+' — '+next.name:tr('Fin de conduite','End of show');byId('nextDesc').textContent=next?next.description:'';byId('countdown').textContent=next?displayTime(next.time-t,true):'—';document.body.className=(show?'show':'')+(show&&next&&next.time-t<=10?' urgent':'');['active','next'].forEach(function(k){var cue=k==='active'?active:next,img=byId(k+'Image');img.style.display=cue&&cue.imageDataUrl?'block':'none';if(cue&&cue.imageDataUrl&&img.getAttribute('src')!==cue.imageDataUrl)img.src=cue.imageDataUrl;});paintCueLabels(c,active,next);if(playing){var a=project.audio;if(a&&t>=a.start&&t<a.start+a.duration&&audio.paused&&!audioAttempted){time=t;syncAudio();}if(t>=d)pause();}}
function save(){hasChanges=true;clearTimeout(saveTimer);saveTimer=setTimeout(function(){if(!db){byId('saveStatus').textContent=tr('Sauvegarde locale indisponible : exportez le projet.','Local saving unavailable: export your project.');return;}try{var tx=db.transaction('draft','readwrite');tx.objectStore('draft').put(project,'current');tx.oncomplete=function(){byId('saveStatus').textContent=tr('Sauvegarde locale automatique','Automatic local save');};tx.onerror=function(){byId('saveStatus').textContent=tr('Échec de sauvegarde : exportez le projet.','Saving failed: export your project.');};}catch(e){byId('saveStatus').textContent=e.message;}},150);}
function button(text,fn){var b=document.createElement('button'),symbol=text===tr('Dupliquer','Duplicate')?'content_copy':text===tr('Supprimer','Delete')?'delete':'add_photo_alternate';S2AMaterial.button(b,symbol,text);b.onclick=fn;return b;}
function render(){byId('title').value=project.title;byId('list').textContent='';byId('marks').textContent='';var c=ordered(),d=duration();c.forEach(function(cue,i){var mark=document.createElement('div');mark.className='mark';mark.style.left=(cue.time/d*100)+'%';var num=document.createElement('span');num.textContent=String(i+1);mark.appendChild(num);byId('marks').appendChild(mark);var row=document.createElement('div');row.className='cue';var label=document.createElement('strong');label.textContent='Cue '+(i+1);row.appendChild(label);var tm=document.createElement('input');tm.value=fmt(cue.time);tm.setAttribute('aria-label',tr('Temps','Time'));tm.onchange=function(){var t=parse(tm.value);if(isFinite(t)&&t>=0){cue.time=t;if(project.audio&&project.audio.cueID===cue.id)project.audio.start=t;save();render();}};row.appendChild(tm);var name=document.createElement('input');name.value=cue.name;name.oninput=function(){cue.name=name.value;save();paint();};row.appendChild(name);var desc=document.createElement('textarea');desc.value=cue.description;desc.oninput=function(){cue.description=desc.value;save();paint();};row.appendChild(desc);row.appendChild(button(tr('Ajouter / changer visuel','Add / change visual'),function(){imageTarget=cue;byId('imageFile').click();}));row.appendChild(button(tr('Dupliquer','Duplicate'),function(){var copy=JSON.parse(JSON.stringify(cue));copy.id=String(Date.now())+Math.random();project.cues.push(copy);save();render();}));row.appendChild(button(tr('Supprimer','Delete'),function(){project.cues=project.cues.filter(function(x){return x.id!==cue.id;});if(project.audio&&project.audio.cueID===cue.id){pause();project.audio=null;audio.removeAttribute('src');}save();render();}));byId('list').appendChild(row);});var a=project.audio;byId('audioBand').style.display=a?'block':'none';if(a){byId('audioBand').textContent=a.name;byId('audioBand').style.left=(a.start/d*100)+'%';byId('audioBand').style.width=(a.duration/d*100)+'%';}paint();}
function applyLanguage(){document.documentElement.lang=lang;byId('lang').value=lang;for(var k in dictionary)if(dictionary.hasOwnProperty(k))byId(k).textContent=dictionary[k][lang==='en'?1:0];var icons={new:'note_add',open:'folder_open',export:'save_as',print:'picture_as_pdf',add:'add_circle',music:'music_note_add',output:'screen_share'};for(var id in icons)if(icons.hasOwnProperty(id))S2AMaterial.decorate(byId(id),icons[id]);render();}
byId('lang').onchange=function(){lang=this.value;try{localStorage.setItem('s2a-language',lang);}catch(e){}applyLanguage();};byId('title').oninput=function(){project.title=this.value;save();};byId('edit').onclick=function(){show=false;paint();};byId('show').onclick=function(){show=true;paint();};byId('play').onclick=function(){if(playing)pause();else play();paint();};byId('restart').onclick=function(){pause();time=0;syncAudio();paint();};byId('add').onclick=function(){project.cues.push({id:String(Date.now())+Math.random(),time:now(),name:'Cue '+(project.cues.length+1),description:'',imageDataUrl:null});render();save();};byId('new').onclick=function(){if(!confirm(tr('Créer une nouvelle conduite ? Exportez d’abord celle-ci si nécessaire.','Create a new show? Export this one first if needed.')))return;pause();time=0;project={title:'',cues:[],audio:null};audio.removeAttribute('src');render();save();};
byId('music').onclick=function(){byId('audioFile').click();};byId('audioFile').onchange=function(){var file=this.files[0];if(!file)return;if(project.audio&&!confirm(tr('Remplacer la musique actuelle ?','Replace the current music?')))return;var reader=new FileReader();reader.onload=function(){pause();var id=String(Date.now());project.audio={name:file.name,data:reader.result,duration:0,start:time,cueID:id};project.cues.push({id:id,time:time,name:file.name,description:'',imageDataUrl:null});audio.src=reader.result;audio.onloadedmetadata=function(){if(project.audio&&project.audio.cueID===id)project.audio.duration=isFinite(audio.duration)?audio.duration:0;render();save();};audio.load();render();save();};reader.readAsDataURL(file);this.value='';};
byId('imageFile').onchange=function(){var file=this.files[0];if(!file||!imageTarget)return;var target=imageTarget,reader=new FileReader();reader.onload=function(){target.imageDataUrl=reader.result;render();save();};reader.readAsDataURL(file);this.value='';};
document.addEventListener('keydown',function(e){if((e.keyCode===32)&&!(/^(INPUT|TEXTAREA|SELECT|BUTTON)$/.test(e.target.tagName))){e.preventDefault();byId('play').click();}});document.addEventListener('gesturestart',function(e){e.preventDefault();},false);var lane=byId('timeline');function eventX(e){return e.touches&&e.touches.length?e.touches[0].clientX:e.changedTouches&&e.changedTouches.length?e.changedTouches[0].clientX:e.clientX;}function move(e){if(!dragging)return;e.preventDefault();var r=lane.getBoundingClientRect();time=Math.max(0,Math.min(duration(),(eventX(e)-r.left)/r.width*duration()));paint();}var resume=false;function begin(e){if(e.type==='mousedown'&&e.button!==0)return;resume=playing;pause();dragging=true;move(e);}function end(e){if(!dragging)return;if(e.type!=='touchcancel')move(e);dragging=false;syncAudio();if(resume)play();paint();}var touchOptions=false;try{var probe=Object.defineProperty({},'passive',{get:function(){touchOptions={passive:false};}});window.addEventListener('s2aprobe',function(){},probe);}catch(e){}lane.addEventListener('touchstart',begin,touchOptions);window.addEventListener('touchmove',move,touchOptions);window.addEventListener('touchend',end,false);window.addEventListener('touchcancel',end,false);lane.addEventListener('mousedown',begin,false);window.addEventListener('mousemove',move,false);window.addEventListener('mouseup',end,false);
function utf8(bytes){var str='';for(var i=0;i<bytes.length;i++)str+=String.fromCharCode(bytes[i]);try{return decodeURIComponent(escape(str));}catch(e){return str;}}
function encode(text){var s=unescape(encodeURIComponent(text)),b=new Uint8Array(s.length);for(var i=0;i<s.length;i++)b[i]=s.charCodeAt(i);return b;}
function unpack(buffer){var v=new DataView(buffer),b=new Uint8Array(buffer),o=0,result={};while(o+30<=b.length&&v.getUint32(o,true)===0x04034b50){var method=v.getUint16(o+8,true),size=v.getUint32(o+18,true),nl=v.getUint16(o+26,true),el=v.getUint16(o+28,true),start=o+30+nl+el;if(method!==0||start+size>b.length)throw Error(tr('ZIP compressé non pris en charge. Ouvrez un export S2A Pilot.','Compressed ZIP unsupported. Open an S2A Pilot export.'));result[utf8(b.subarray(o+30,o+30+nl))]=b.subarray(start,start+size);o=start+size;}if(!result['conduite.json'])throw Error(tr('Conduite introuvable dans le ZIP.','Show data missing from ZIP.'));return result;}
function dataURL(bytes,name){var type=/\.(png|jpg|jpeg|webp)$/i.test(name)?'image/'+(/png$/i.test(name)?'png':/webp$/i.test(name)?'webp':'jpeg'):/\.wav$/i.test(name)?'audio/wav':'audio/mpeg',s='';for(var i=0;i<bytes.length;i++)s+=String.fromCharCode(bytes[i]);return 'data:'+type+';base64,'+btoa(s);}
byId('open').onclick=function(){byId('projectFile').click();};byId('projectFile').onchange=function(){var file=this.files[0];if(!file)return;var reader=new FileReader();reader.onload=function(){var previous=project;try{var entries=/\.zip$/i.test(file.name)?unpack(reader.result):null,m=JSON.parse(entries?utf8(entries['conduite.json']):reader.result);if(m.format==='s2a-legacy-project')project=m.project;else{if(!Array.isArray(m.cues))throw Error('Invalid project');project={title:m.title||'',cues:[],audio:null};var audioCount=0; m.cues.forEach(function(c){project.cues.push({id:String(c.index),time:Number(c.time)||0,name:c.name||'Cue',description:c.description||'',imageDataUrl:c.imagePath&&entries&&entries[c.imagePath]?dataURL(entries[c.imagePath],c.imagePath):null});(c.mediaActions||[]).forEach(function(a){if(a.kind==='audio'){audioCount++;if(!project.audio&&entries&&entries[a.path]){var bytes=entries[a.path];project.audio={name:a.name||a.path,data:dataURL(bytes,a.path),duration:Math.max(0,(Number(a.outPoint)||Number(a.duration)||0)-(Number(a.inPoint)||0)),inPoint:Number(a.inPoint)||0,start:Number(c.time)||0,cueID:String(c.index)};}}});});if(audioCount>1)alert(tr('Cet ancien navigateur ne joue que la première musique. Toutes les Cues sont conservées.','This older browser plays only the first music track. All Cues are retained.'));}pause();time=0;if(project.audio)audio.src=project.audio.data;else audio.removeAttribute('src');render();save();}catch(e){project=previous;alert(e.message);}};if(/\.zip$/i.test(file.name))reader.readAsArrayBuffer(file);else reader.readAsText(file);this.value='';};
function download(blob,name){var url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;if('download' in a){document.body.appendChild(a);a.click();document.body.removeChild(a);}else window.open(url,'_blank');setTimeout(function(){URL.revokeObjectURL(url);},60000);}
byId('export').onclick=function(){download(new Blob([JSON.stringify({format:'s2a-legacy-project',version:1,project:project})],{type:'application/json'}),(project.title||'S2A-Pilot')+'.s2apilot.json');};
byId('print').onclick=function(){var sheet=byId('printSheet');sheet.textContent='';var title=document.createElement('h1');title.textContent=project.title||tr('Conduite technique','Technical cue sheet');sheet.appendChild(title);ordered().forEach(function(c,i){var row=document.createElement('article');var h=document.createElement('h2');h.textContent=(i+1)+' — '+fmt(c.time)+' ('+fmt(duration()-c.time)+') — '+c.name;var p=document.createElement('p');p.textContent=c.description;row.appendChild(h);row.appendChild(p);sheet.appendChild(row);});window.print();};
if(window.indexedDB){try{var req=indexedDB.open('s2a-pilot-legacy',1);req.onupgradeneeded=function(){req.result.createObjectStore('draft');};req.onsuccess=function(){db=req.result;var get=db.transaction('draft','readonly').objectStore('draft').get('current');get.onsuccess=function(){if(get.result&&!hasChanges){project=get.result;if(project.audio)audio.src=project.audio.data;render();}byId('saveStatus').textContent=tr('Sauvegarde locale prête','Local saving ready');};};req.onerror=function(){byId('saveStatus').textContent=tr('Sauvegarde locale indisponible : exportez votre projet.','Local saving unavailable: export your project.');};}catch(e){byId('saveStatus').textContent=e.message;}}
if('serviceWorker' in navigator&&(location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1'))navigator.serviceWorker.register('../service-worker.js').catch(function(){});
applyLanguage();setInterval(function(){if(playing)paint();},100);

function paintCueLabels(c,active,next){
 var host=byId('cueLabels'),width=host.clientWidth,d=duration(),key=JSON.stringify([width,show,active?active.id:null,lang,c]);if(key===labelKey)return;labelKey=key;host.textContent='';
 var priority=active?[active]:[],future=[],past=[],i;for(i=0;i<c.length;i++){if(c[i]===active)continue;if(c[i].time>now())future.push(c[i]);else past.push(c[i]);}priority=priority.concat(future,past.reverse());var used=[];
 for(i=0;i<priority.length;i++){var cue=priority[i],el=document.createElement('div'),txt=document.createElement('i');el.className='cueBubble'+(cue===active?' current':cue.time<=now()?' completed':'');txt.textContent=cue.name||'Cue';el.appendChild(txt);host.appendChild(el);var w=el.offsetWidth,left=Math.max(0,Math.min(width-w,cue.time/d*width-w/2)),hit=false;for(var j=0;j<used.length;j++)if(left<used[j][1]+6&&left+w>used[j][0]-6)hit=true;if(hit)host.removeChild(el);else{el.style.left=left+'px';used.push([left,left+w]);}}
 var following=byId('following');following.textContent='';var title=document.createElement('small');title.textContent=tr('ENSUITE','AFTER THAT');following.appendChild(title);var start=next?c.indexOf(next)+1:c.length;for(i=start;i<Math.min(c.length,start+4);i++){var row=document.createElement('div'),name=document.createElement('div'),timeLabel=document.createElement('time');row.className='followingRow';name.textContent=c[i].name;timeLabel.textContent=displayTime(c[i].time);row.appendChild(name);row.appendChild(timeLabel);following.appendChild(row);}
}
window.addEventListener('resize',function(){labelKey='';paint();});

})();
